export interface MediaItem {
  title: string
  thumbnail: string
  mediaUrl: string
  category: string
  type: "image" | "video"
  featured?: boolean
}

export const mediaItems: MediaItem[] = [
  // === Animations ===
  {
    title: "DHC4K Animation for Kids Connect",
    thumbnail: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622246/DHC4K_ANIMATION_FOR_KIDS_CONNECT_pmvxcy.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622246/DHC4K_ANIMATION_FOR_KIDS_CONNECT_pmvxcy.mp4",
    category: "Animations",
    type: "video",
    featured: true,
  },
  {
    title: "Loud It Tees",
    thumbnail: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622171/LOUD_IT_TEES_etpqk2.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622171/LOUD_IT_TEES_etpqk2.mp4",
    category: "Animations",
    type: "video",
  },
  {
    title: "Master Mode",
    thumbnail: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622171/Master_Mode_A_cheerful_cartoon_boy_standing_jyoktr.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622171/Master_Mode_A_cheerful_cartoon_boy_standing_jyoktr.mp4",
    category: "Animations",
    type: "video",
  },
  {
    title: "Whisk Animation",
    thumbnail: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622165/Whisk_qgmymtnzktyyugzm1cnjftytyznlrtl5ato30in_edzlvt.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622165/Whisk_qgmymtnzktyyugzm1cnjftytyznlrtl5ato30in_edzlvt.mp4",
    category: "Animations",
    type: "video",
  },
  {
    title: "Pixar Hospital Room Animation",
    thumbnail: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622164/Pixar_Hospital_Room_Animation_Ready_adohgr.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622164/Pixar_Hospital_Room_Animation_Ready_adohgr.mp4",
    category: "Animations",
    type: "video",
  },

  // === Birthday Designs ===
  {
    title: "Pastor Tosin Birthday Design",
    thumbnail: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622314/Pst_Tosin_fy7syd.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622314/Pst_Tosin_fy7syd.png",
    category: "Birthday Designs",
    type: "image",
  },
  {
    title: "Zoe Birthday Celebration",
    thumbnail: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622308/Zoe_llgueh.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622308/Zoe_llgueh.jpg",
    category: "Birthday Designs",
    type: "image",
    featured: true,
  },
  {
    title: "Big Sis Birthday",
    thumbnail: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622308/Big-sis_udmlbs.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622308/Big-sis_udmlbs.jpg",
    category: "Birthday Designs",
    type: "image",
  },
  {
    title: "Sister Chioma",
    thumbnail: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622307/Sister_Chioma_zvyj65.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622307/Sister_Chioma_zvyj65.png",
    category: "Birthday Designs",
    type: "image",
  },
  {
    title: "Tega Birthday Design",
    thumbnail: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622305/TEGA_r2cdii.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622305/TEGA_r2cdii.jpg",
    category: "Birthday Designs",
    type: "image",
  },
  {
    title: "Bro David Ehijayd",
    thumbnail: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622305/EDO_yzy5ao.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622305/EDO_yzy5ao.jpg",
    category: "Birthday Designs",
    type: "image",
  },
  {
    title: "Sis Queen Birthday",
    thumbnail: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622303/Sis-Queen_egqjef.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622303/Sis-Queen_egqjef.jpg",
    category: "Birthday Designs",
    type: "image",
  },
  {
    title: "Pwealth Celebration",
    thumbnail: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622304/PWEALTH_c2z9hk.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622304/PWEALTH_c2z9hk.jpg",
    category: "Birthday Designs",
    type: "image",
  },
  {
    title: "Jerry Birthday",
    thumbnail: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622303/Jerry_se9lde.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622303/Jerry_se9lde.jpg",
    category: "Birthday Designs",
    type: "image",
  },
  {
    title: "Emilex Birthday",
    thumbnail: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622300/Emilex_ebmxsh.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622300/Emilex_ebmxsh.png",
    category: "Birthday Designs",
    type: "image",
  },
  {
    title: "PJ 2025 Birthday",
    thumbnail: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622300/PJ-2025_kwme1d.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622300/PJ-2025_kwme1d.jpg",
    category: "Birthday Designs",
    type: "image",
  },
  {
    title: "Chizaram Celebration",
    thumbnail: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622298/CHIZARAM_xtjh1q.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622298/CHIZARAM_xtjh1q.jpg",
    category: "Birthday Designs",
    type: "image",
  },
  {
    title: "Bro Efe Birthday",
    thumbnail: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622297/Bro-Efe_lxaax7.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622297/Bro-Efe_lxaax7.jpg",
    category: "Birthday Designs",
    type: "image",
  },

  // === Graphics Design ===
  {
    title: "Summer Smarts",
    thumbnail: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622376/Summer-Smarts_rmd9pi.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622376/Summer-Smarts_rmd9pi.jpg",
    category: "Graphics Design",
    type: "image",
    featured: true,
  },
  {
    title: "Eat Light, Eat Right",
    thumbnail: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622374/EAT-LIGHT_-EAT-RIGHT_o1kak9.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622374/EAT-LIGHT_-EAT-RIGHT_o1kak9.jpg",
    category: "Graphics Design",
    type: "image",
    featured: true,
  },
  {
    title: "Bright Smiles",
    thumbnail: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622373/Bright-Smiles_mnccx6.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622373/Bright-Smiles_mnccx6.jpg",
    category: "Graphics Design",
    type: "image",
  },
  {
    title: "HSLHS July Teaser",
    thumbnail: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622371/HSLHS-JULY-2024---TEASER-2_lsll3r.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622371/HSLHS-JULY-2024---TEASER-2_lsll3r.jpg",
    category: "Graphics Design",
    type: "image",
  },
  {
    title: "Teaser 2",
    thumbnail: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622370/Teaser-2_dq3q49.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622370/Teaser-2_dq3q49.jpg",
    category: "Graphics Design",
    type: "image",
  },
  {
    title: "ORDER Kids Magazine September",
    thumbnail: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622368/ORDER-2025-Kids-Magazine-September_pl57su.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622368/ORDER-2025-Kids-Magazine-September_pl57su.jpg",
    category: "Graphics Design",
    type: "image",
  },
  {
    title: "HED Card",
    thumbnail: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622367/HED-Card_oei5ed.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622367/HED-Card_oei5ed.jpg",
    category: "Graphics Design",
    type: "image",
  },
  {
    title: "July Mag Ad",
    thumbnail: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622367/2025_July_Mag_Ad_ORDER_eo6gpk.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622367/2025_July_Mag_Ad_ORDER_eo6gpk.jpg",
    category: "Graphics Design",
    type: "image",
  },
  {
    title: "IPPC 2024 Teaser 5",
    thumbnail: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622366/2024-IPPC-teaser-5_rtaw6x.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/image/upload/v1761622366/2024-IPPC-teaser-5_rtaw6x.jpg",
    category: "Graphics Design",
    type: "image",
  },

  // === Logo Montage ===
  {
    title: "PJ Image and Sound",
    thumbnail: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622494/PJ_IMAGE_AND_SOUND_le8dru.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622494/PJ_IMAGE_AND_SOUND_le8dru.mp4",
    category: "Logo Montage",
    type: "video",
    featured: true,
  },
  {
    title: "Dcn Tona Intro",
    thumbnail: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622472/Dcn_Tona_Intro_tcbv81.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622472/Dcn_Tona_Intro_tcbv81.mp4",
    category: "Logo Montage",
    type: "video",
  },
  {
    title: "HFTF Fire & Sound",
    thumbnail: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622468/HFTF_FIRE_AND_SOUND_sxq8fn.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622468/HFTF_FIRE_AND_SOUND_sxq8fn.mp4",
    category: "Logo Montage",
    type: "video",
  },
  {
    title: "CELVZTM Award Montage",
    thumbnail: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622454/CELVZTM_AWARD_AND_RECOGNITION_MONTAGE_rme2pd.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622454/CELVZTM_AWARD_AND_RECOGNITION_MONTAGE_rme2pd.mp4",
    category: "Logo Montage",
    type: "video",
  },
  {
    title: "HFTF Fire 5.0",
    thumbnail: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622452/HFTF_FIRE_5.0_FIRE_LOGO_lykd24.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622452/HFTF_FIRE_5.0_FIRE_LOGO_lykd24.mp4",
    category: "Logo Montage",
    type: "video",
  },
  {
    title: "Elaborate Final",
    thumbnail: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622447/ELABORATE_FINAL_ysdos7.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622447/ELABORATE_FINAL_ysdos7.mp4",
    category: "Logo Montage",
    type: "video",
  },
  {
    title: "Train Move and Hew",
    thumbnail: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622437/TRAIN_MOVE_AND_HEW_LOGO_NEW_ihc0eb.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622437/TRAIN_MOVE_AND_HEW_LOGO_NEW_ihc0eb.mp4",
    category: "Logo Montage",
    type: "video",
  },
  {
    title: "LCHSFMA Montage",
    thumbnail: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622436/LCHSFMA_MONTAGE_cwgmz5.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622436/LCHSFMA_MONTAGE_cwgmz5.mp4",
    category: "Logo Montage",
    type: "video",
  },
  {
    title: "1st Quarter Award Montage",
    thumbnail: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622436/1st_Quater_Award_Montage_Updated_cidchu.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622436/1st_Quater_Award_Montage_Updated_cidchu.mp4",
    category: "Logo Montage",
    type: "video",
  },
  {
    title: "Foundation School Montage",
    thumbnail: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622431/Foundation_School_Montage_gjxwnj.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622431/Foundation_School_Montage_gjxwnj.mp4",
    category: "Logo Montage",
    type: "video",
  },
  {
    title: "EOTYCM Updated",
    thumbnail: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622430/EOTYCM_UPDATED_2023_fmwnxh.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622430/EOTYCM_UPDATED_2023_fmwnxh.mp4",
    category: "Logo Montage",
    type: "video",
  },
  {
    title: "DES Logo Motion",
    thumbnail: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622426/DES_LOGO_MOTION_our5qv.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622426/DES_LOGO_MOTION_our5qv.mp4",
    category: "Logo Montage",
    type: "video",
  },

  // === Motion Graphics ===
  {
    title: "Kids Outreach Train",
    thumbnail: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622884/KIDS_OUTREACH_TRAIN_zi2mmh.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622884/KIDS_OUTREACH_TRAIN_zi2mmh.mp4",
    category: "Motion Graphics",
    type: "video",
  },
  {
    title: "Pastor Chris Birthday Filler",
    thumbnail: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622870/HAPPY_BIRTHDAY_FILLER_2_PASTOR_CHRIS_rahymj.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622870/HAPPY_BIRTHDAY_FILLER_2_PASTOR_CHRIS_rahymj.mp4",
    category: "Motion Graphics",
    type: "video",
    featured: true,
  },
  {
    title: "Poesie de l'Amour",
    thumbnail: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622868/Po%C3%A9sie_de_l_amour_by_Saint_Chidi_fs76vp.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622868/Po%C3%A9sie_de_l_amour_by_Saint_Chidi_fs76vp.mp4",
    category: "Motion Graphics",
    type: "video",
  },
  {
    title: "Adult Picture Collage",
    thumbnail: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622863/Adult_Picture_Collage_fkhiav.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622863/Adult_Picture_Collage_fkhiav.mp4",
    category: "Motion Graphics",
    type: "video",
  },
  {
    title: "HFTF 5.0 Official Trailer",
    thumbnail: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622845/HFTF_5.0_OFFICIAL_TRAILER_HD_dnikiy.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622845/HFTF_5.0_OFFICIAL_TRAILER_HD_dnikiy.mp4",
    category: "Motion Graphics",
    type: "video",
  },
  {
    title: "HFTF Intro Montage",
    thumbnail: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622838/HFTF_INTRO_MONTAGE_rypopy.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622838/HFTF_INTRO_MONTAGE_rypopy.mp4",
    category: "Motion Graphics",
    type: "video",
  },
  {
    title: "Unveiling Award",
    thumbnail: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622770/UNVAILING_AWARD_iomhh3.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622770/UNVAILING_AWARD_iomhh3.mp4",
    category: "Motion Graphics",
    type: "video",
    featured: true,
  },
  {
    title: "JAC 1K Hours Prayed",
    thumbnail: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622761/JAC_1k_HOURS_PRAYED_ywdqhu.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622761/JAC_1k_HOURS_PRAYED_ywdqhu.mp4",
    category: "Motion Graphics",
    type: "video",
  },
  {
    title: "Healthy Kids",
    thumbnail: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622756/Healthy_Kids_Video_Creation_miuunb.jpg",
    mediaUrl: "https://res.cloudinary.com/drajqudmp/video/upload/v1761622756/Healthy_Kids_Video_Creation_miuunb.mp4",
    category: "Motion Graphics",
    type: "video",
  },
]
